### PR TITLE
Update bundled FFmpeg to 3.0.5, update build deps, enable NVENC

### PR DESCRIPTION
**Pull request by eumagga0x2a**
Hello,

the upstream Avidemux has moved to FFmpeg 3.0.5, a good reason to release an updated Fedora package with updated FFmpeg and some of the latest fixes. These fixes include:

1. Encoding with NVENC for H.264 and H.265 actually works now, a NVIDIA graphics card starting with Kepler and very recent binary NVIDIA drivers provided (methinks this is the main functional highlight);
2. A busy loop when playing videos without audio has been fixed;
3. The TS demuxer won't give up too early looking for audio;
4. Navigation in 1s/2s/4s steps works now, "Go to Time" is not limited to the closest keyframe;
5. Audio device being set to "Dummy" if the configuration file exists but is rejected for some reason is fixed;
6. The Qt x265 configuration dialog now safeguards agains (some of the) settings which would be rejected by the encoder;
7. A bit of visual polish for the volume widget.

Last but not least, the patch for building with system a52dec, libmad and libass instead of the bundled ones has been accepted upstream with very minor changes. I replaced `avidemux-2.6.10-bundled_libs.patch` with the upstream solution.

All the upstream patches are concatenated and where necessary merged together into a single file `avidemux-2.6.15-drop-after-2.6.16.patch` while keeping all commit headers. This patch should be dropped once 2.6.16 is released. The `avidemux-2.6.15-disable-vpx-decoder-plugin.patch` is not upstreamed yet and should be left as-is for now.

js-devel and ffmpeg-devel are not needed anymore (they were not needed for 2.6.15 as well, but just slipped through), opus support is nice-to-have and NVENC resulting in nvenc-devel as build dependency is the highlight.

I'm unsure how to include big additional sources like ffmpeg-3.0.5.tar.bz2 properly, but just uploading the archive to the repository should be trivial. I've added the matching md5sum (I still know very little about RPM, so I wonder if an up-to-date hashing algorithm may be used?) to the `sources` file.

The package has been successfully test-built and functionally tested on Fedora 24 x86_64 so far.

Thanks!

### CODE REVIEW

**Comment by sergiomb2** [comment]
Hi , first of all I don't know if others monitorize PRs, so if not please open a quick bug report in RPmfusion bugzilla pointing to this PR.
About your patch can't we use ffmpeg of the system (ffmpeg 3.1.x) ?

**Comment by eumagga0x2a** [comment]
> can't we use ffmpeg of the system (ffmpeg 3.1.x) ?

AFAIK no, unfortunately not. FFmpeg is bundled because it is patched to gain access to some private interfaces. I'm not aware of any work to change this state of affairs, at least not ATM.

Will open a bug later today, thanks.

**Comment by leigh123linux** [comment]
Forward the ffmpeg patches upstream as I seriously doubt we will bundle ffmpeg just for avidemux
 
>AFAIK no, unfortunately not. FFmpeg is bundled because it is patched to gain access to some private >interfaces. I'm not aware of any work to change this state of affairs, at least not ATM.

**Comment by eumagga0x2a** [comment]
As noted in the comment [https://bugzilla.rpmfusion.org/show_bug.cgi?id=4386#c3](https://bugzilla.rpmfusion.org/show_bug.cgi?id=4386#c3), FFmpeg must be patched to not require `--enable-nonfree` when enabling NVENC. I've adapted the aforementioned patch to 3.0.5 and added it to the list of sources. Tieing the application of this additional patch to the test in `admFFmpegBuild.cmake` for UNIX being set is logically questionable but will hopefully do for now.

I've moved the cmake/FFmpeg/NVENC part of the all-in-one patch `avidemux-2.6.15-drop-after-2.6.16.patch` to a separate patch and changed the format of commit headers as well as added one missing header.

The updated package has been test-built and briefly tested on Fedora 24 x86_64.

**Comment by eumagga0x2a** [comment]
I'm going to close this pull request in order to open a new one immediately, selfishly adding even more isolated upstream fixes and returning to a single all-in-one patch for all backports, including the upstream patch for the bundled ffmpeg to not require `--enable-nonfree` for NVENC.

**Comment by sergiomb2** [comment]
hum if you split all in a bunch of patches you will have better changes to have something approved .

**Pull request closed without merging**
