### PR TITLE
Update bundled FFmpeg to 3.0.5, update build deps, enable NVENC, backport various upstream fixes

### PR DESCRIPTION
**Pull request by eumagga0x2a**
This is a followup to [https://github.com/rpmfusion/avidemux/pull/2](https://github.com/rpmfusion/avidemux/pull/2), with the all-in-one patch split into individual patches. The patches named `avidemux-00xx-*.patch` are backports to be dropped after 2.6.16. Those from 0001 to 0004 are must-haves, the last two fix just the visuals.

### CODE REVIEW

**Comment by sergiomb2** [comment]
Hi, 

> This is a followup to #2, with the all-in-one patch split into individual patches.

Each individual patch should be one commit , for better reading and to be possible cherry-pick individual commits ... , I'm not the maintainer of avidemux but I could help maintainer, commit 4518a3e is very hard to read for me .
Also it will be hard bundled FFmpeg to 3.0.5, I don't understand the logic here , if we not bundle ffmpeg before why we should bundle it now ? anyway RPMFusion made the decision (I was one of the mentors ) to have ffmpeg 3.1.x in F24 instead 3.0.x , but in rawhide we already have ffmpeg 3.2.x , also already we have one request (in bugzilla) to update F25 to ffmpeg 3.2.x ( which shouldn't happen, BTW ) . Anyway if we can't use external ffmpeg, I think avidemux have one "internal" ffmpeg and we may try use that on branches where external ffmpeg is incompatible, but we need open a ticket with one bundle request  ... this process try unbundle all sources sometimes is hard , but by fedora guidelines we always should try it ... 
Hope be one useful comment , as I explain I haven't much power to made one decision ... 
Thanks !

**Comment by eumagga0x2a** [comment]
> Each individual patch should be one commit , for better reading and to be possible cherry-pick individual commits

For obvious reasons, this is not how things can work, because some commits modify or fix previous commits, so they have to be merged into a single patch. I've preserved commit headers, which should allow to trace their origin. Also some commits modify files which were renamed upstream after the release of 2.6.15 like `cmake/admFFmpegBuild.cmake`, where I had to backport.

Apart from that I've left only those patches merged into a single file which really belong together.

> Also it will be hard bundled FFmpeg to 3.0.5, I don't understand the logic here , if we not bundle ffmpeg before why we should bundle it now ?

RPMFusion bundles FFmpeg alone by shipping any Avidemux package. The upstream has switched from 3.0.3 to 3.0.5 post-release, the release Avidemux tarball contains an outdated ffmpeg tarball, so unless you are going to modify the Avidemux tarball the only way to deliver 3.0.5 is to include its tarball as an additional source.

**Comment by eumagga0x2a** [comment]
Out of the blue, Avidemux 2.6.16 was released today (I expected this to happen in the timeframe of late January or February 2017). Hence I close this one, will open a new PR for an update to 2.6.16 once my local builds have been successfully tested.

My apologies for the trouble.

**Comment by sergiomb2** [comment]
For example avidemux-0012-vdpau-to-upper.patch couldn't be in one different commit ? I don't understand you . 
About bundles ffmpeg are you saying that avidemux already use internal ffmpeg ? if so, your bundle makes more sense , what doesn't make sense is have BuildRequires: ffmpeg-devel in avidemux.spec 

Thanks.

**Comment by eumagga0x2a** [comment]
> For example avidemux-0012-vdpau-to-upper.patch couldn't be in one different commit ?

Not `avidemux-0012-vdpau-to-upper.patch` but `avidemux-0008-navigation.patch` consists of three related commits merged into a single patch (otherwise it is impossible to revert the changes with `patch -R`). All this is obsolete now as 2.6.16 has been totally unexpectedly released (which is very good news anyway).

> About bundles ffmpeg are you saying that avidemux already use internal ffmpeg ?

Yet, this is correct. Avidemux was and is using its own internal, bundled, patched ffmpeg (`avidemux_core/ffmpeg_package`).

**Pull request closed without merging**
